services:
  postgres:
    build:
      context: .
      dockerfile: Dockerfile
    image: postgres
    restart: always
    container_name: ${PG_CONTAINER_NAME}
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
       - db:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
    db:
      external: false